import { chromium } from 'playwright';
const [,, url, wArg] = process.argv; const W = +(wArg||1440);
const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36';
const b = await chromium.launch(); const ctx = await b.newContext({viewport:{width:W,height:900},userAgent:UA,reducedMotion:'reduce'}); const p = await ctx.newPage();
await p.goto(url,{waitUntil:'domcontentloaded'}); await p.waitForTimeout(2500);
const btn = await p.$('#onetrust-accept-btn-handler'); if (btn) { try { await btn.click({timeout:1000}); } catch{} await p.waitForTimeout(400); }
await p.mouse.move(2, 880);
const sels = ['.top-navigation','.top-navigation__top-bar','.top-navigation__top-bar-wrapper','.drop-down__label-wrapper','.drop-down__select-icon','.drop-down__label','.top-navigation__main-bar','.top-navigation__logo','.top-navigation__logo-image','.top-navigation__logo-image--desktop','.top-navigation__logo-image--mobile','.top-navigation__logo-hamburger','.navigation-menu','.navigation-menu__list','.navigation-menu__list-item--level-1','.navigation-menu__list-item-link--level-1','.breadcrumb','.cmp-breadcrumb','.cmp-breadcrumb__navigation','.cmp-breadcrumb__list','.cmp-breadcrumb__item','.cmp-breadcrumb__navigation-item','.cmp-breadcrumb__navigation-item--active','.cmp-breadcrumb__navigation-item a','.cmp-experiencefragment--header-xf','.cmp-experiencefragment--footer-xf','.cmp-experiencefragment--footer-xf .cmp-container','.cmp-experiencefragment--footer-xf .container.responsivegrid','.cmp-experiencefragment--footer-xf .image','.cmp-experiencefragment--footer-xf .cmp-image','.cmp-experiencefragment--footer-xf .cmp-image__image','.footer','.footer-links','.footer-links__sites','.footer-links__sites li','.footer-links__sites a','.cmp-experiencefragment--footer-xf .text','.cmp-experiencefragment--footer-xf .cmp-text','.cmp-experiencefragment--footer-xf .separator','.cmp-experiencefragment--footer-xf .cmp-separator','.cmp-experiencefragment--footer-xf hr','.navigation-menu__list-item-link--level-1[aria-current], .navigation-menu__list-item--level-1.active, .navigation-menu__list-item-link--level-1.active'];
const out = await p.evaluate((sels)=>{ const props=['display','position','top','backgroundColor','backgroundImage','color','fontFamily','fontSize','fontWeight','lineHeight','letterSpacing','textTransform','textDecoration','paddingTop','paddingRight','paddingBottom','paddingLeft','marginTop','marginRight','marginBottom','marginLeft','height','width','maxWidth','minHeight','borderRadius','borderBottom','borderTop','justifyContent','alignItems','gap','flexDirection','overflow','zIndex','textAlign','boxSizing','listStyle']; const r={}; for (const s of sels){ const els=[...document.querySelectorAll(s)]; r[s]=els.slice(0,6).map(el=>{const rc=el.getBoundingClientRect(); const cs=getComputedStyle(el); const o={rect:[Math.round(rc.left),Math.round(rc.top+scrollY),Math.round(rc.width),Math.round(rc.height)],text:(el.textContent||'').replace(/\s+/g,' ').trim().slice(0,40),cls:(el.className||'').toString().slice(0,80)}; for(const k of props){const v=cs[k]; if(v&&v!=='none'&&v!=='normal'&&v!=='auto'&&v!=='0px'&&v!=='rgba(0, 0, 0, 0)'&&v!=='static'&&v!=='visible'&&v!=='start'&&v!=='content-box') o[k]=v;} for (const pe of ['::before','::after']){const pc=getComputedStyle(el,pe); if(pc.content&&pc.content!=='none'&&pc.content!=='normal'){o[pe]={content:pc.content,w:pc.width,h:pc.height,bg:pc.backgroundColor,bgi:pc.backgroundImage,pos:pc.position,top:pc.top,left:pc.left,bottom:pc.bottom,border:pc.borderBottom,transform:pc.transform};}} return o;}); } return r; }, sels);
console.log(JSON.stringify({url,W,docH: await p.evaluate(()=>document.documentElement.scrollHeight), out},null,1));
await b.close();
