import { chromium } from 'playwright';
const W = +process.argv[2]; const url = 'http://localhost:8793/stardust/prototypes/home-proposed.html';
const lift = JSON.parse((await import('fs')).readFileSync(`stardust/replica/capture/lift-home-${W}.json`,'utf8'));
const b = await chromium.launch(); const p = await b.newPage({ viewport:{width:W,height:900} });
await p.goto(url,{waitUntil:'networkidle'}); await p.waitForTimeout(800);
const sel = { h1:'main h1', sub:'main .hero__sub b', subm:'main .hero__sub-mobile i', hr:'main .hero__rule hr', lede:'main .hero__lede p', hand:'main .hero__hand img', redhr:'main .hero__red-rule hr', iframe:'main iframe',
 h2:'main h2', pb:'main .promo__text b', phr:'main .promo__rule hr', shop:'main .promo__button a', img1:'main [data-card=play] img', p1:'main [data-card=play] p', btn1:'main [data-card=play] a', img2:'main [data-card=host] img', btn2:'main [data-card=host] a',
 icon:'.v-lead-generation-form__icon', h4:'main h4', cta:'.v-lead-generation-form__cta-text p', lab1:'label[for=email-value-id]', in1:'#email-value-id', lab2:'label[for=zipcode-value-id]', in2:'#zipcode-value-id', join:'.subscribe-button', terms:'.v-lead-generation-form__terms-description p',
 hero:'.band--hero', promo:'.band--promo', ph:'.band--play-host', news:'.band--newsletter', footer:'footer', flogo:'footer img', flink1:'footer .footer-links__sites a', hdr:'header', nav1:'#HOME-label', crumb:'.cmp-breadcrumb__navigation-item--active' };
const out = await p.evaluate((sel)=>{ const r={}; for(const [k,s] of Object.entries(sel)){ const e=document.querySelector(s); if(!e){r[k]=null;continue;} const c=e.getBoundingClientRect(); const cs=getComputedStyle(e); r[k]=[Math.round(c.x),Math.round(c.y+scrollY),Math.round(c.width),Math.round(c.height), cs.fontSize, cs.lineHeight, cs.fontFamily.split(',')[0]]; } r.docH=document.documentElement.scrollHeight; return r; }, sel);
const byText = (t)=>lift.elements.find(e=>e.text&&e.text.startsWith(t)); const byCls=(c,i=0)=>lift.elements.filter(e=>(e.cls||'').includes(c))[i]; const byTag=(t,i=0)=>lift.elements.filter(e=>e.tag===t)[i];
const L = { h1:byText('Red Ball Tennis'), sub:byText('RAW THE LINES'), subm:byText('RAW THE LINES'), hr:byCls('cmp-separator__horizontal-rule',0), lede:byText('Red Ball Tennis drops'), hand:W===360?byCls('cmp-image__image',0):null, redhr: W===360?byCls('cmp-separator__horizontal-rule',0):null, iframe:lift.elements.find(e=>e.tag==='iframe'&&e.rect[2]>0),
 h2:byText('REDESIGNED'), pb:byText('Get the official'), phr:byCls('cmp-separator__horizontal-rule',1), shop:byCls('cmp-button button-core',0), img1:byCls('cmp-image__image',W===360?1:0), p1:byText('Game on'), btn1:byCls('cmp-button button-core',1), img2:byCls('cmp-image__image',W===360?2:1), btn2:byCls('cmp-button button-core',2),
 icon:byCls('v-lead-generation-form__icon'), h4:byText('RED IS IN'), cta:byText('SIGN UP'), lab1:byText('EMAIL'), in1:lift.elements.find(e=>e.id==='email-value-id'), lab2:byText('ZIP/POSTAL'), in2:lift.elements.find(e=>e.id==='zipcode-value-id'), join:byText('*JOIN'), terms:byText('*By clicking'),
 hero:byCls('horizontal-bottom-red-stripe',0), promo:byCls('horizontal-bottom-red-stripe',1), ph:byCls('full-width justify-content_space-around aem-G',0), news:byCls('horizontal-bottom-red-stripe',2), footer:byCls('cmp-experiencefragment--footer-xf'), flogo:byCls('cmp-image__image',W===360?3:2), flink1:byText('Terms & Conditions'), hdr:byCls('cmp-experiencefragment--header-xf'), nav1:lift.elements.find(e=>e.id==='HOME-label'), crumb:byCls('cmp-breadcrumb__navigation-item--active') };
console.log(`W=${W} proto docH ${out.docH} live docH ${lift.docHeight}`);
for (const k of Object.keys(sel)) { const a=out[k], l=L[k]; const lr=l?l.rect:null; const flag=(a&&lr)?(Math.abs(a[0]-lr[0])>1||Math.abs(a[1]-lr[1])>1||Math.abs(a[2]-lr[2])>1||Math.abs(a[3]-lr[3])>1?'  <<<':''):''; console.log(k.padEnd(7),'proto',JSON.stringify(a&&a.slice(0,4)),a?a.slice(4).join('/'):'', '| live',JSON.stringify(lr), l&&l.s?[l.s.fontSize,l.s.lineHeight].join('/'):'', flag); }
await b.close();
